services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=file_upload_db
            - DB_USERNAME=postgres
            - DB_PASSWORD=secret
        depends_on:
            - db

    db:
        image: postgres:latest
        container_name: postgres-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: file_upload_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"

    # Nginx service
    web:
        image: nginx:latest
        container_name: nginx-server
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        depends_on:
            - app
